# Generated by Django 4.1.7 on 2023-04-09 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinates',
            name='time',
            field=models.CharField(default='2023-04-8T12:00:00', max_length=25),
        ),
    ]
